src/chat/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from rest_framework.authtoken.views import obtain_auth_token

from . import views


router = DefaultRouter()

handler404 = views.error_404

app_name = "chat"
urlpatterns = [
    path("open_chat/<int:user_id>", views.open_chat, name="open_chat"),
    path("send_message/", views.send_message, name="send_message"),
    path("alter_message/", views.alter_message, name="alter_message"),
    path("delete_message/", views.delete_message, name="delete_message"),
    path("list/", views.chat_list),

    path('api-token-auth/', obtain_auth_token),
    path("is_authed/", views.is_authed),
    path("<int:companion_id>/", views.get_chat_data),
    path("api/", include(router.urls)),
]

src/product/urls.py
from django.urls import path


from . import views


app_name = "product"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("add_product_to_basket/<int:product_id>/", view=views.add_product_to_basket, name="add_product_to_basket"),
    path("remove_product_from_basket/<int:product_id>/", view=views.remove_product_from_basket, name="remove_product_from_basket"),
    path("basket/", view=views.basket, name="basket"),
    path("approve_basket/", views.approve_basket, name="approve_basket"),
    path("payment_success/<int:basket_id>", views.payment_success, name="payment_success"),
    path("purchase_history/", views.purchase_history, name="purchase_history"),
    path("about_product/<int:product_id>/", views.about_product, name="about_product"),

    path("add_like_on_review/<int:review_id>/", view=views.add_like_on_review, name="add_like_on_review")
]

src/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("user.urls")),
    path('product/', include("product.urls")),
    path('chat/', include("chat.urls")),
    path('social_network/', include("social_network.urls")),


    path("", RedirectView.as_view(pattern_name="product:index"), name="default")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("signup/", views.sign_up, name="signup"),

    path("profile/", views.profile, name="account_profile"),
    path("edit/", views.edit_profile, name="edit_profile"),
    path("set_online_status/", views.set_online_status, name="set_online_status"),
]

src/user/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

User = get_user_model()

class UserImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to="user_images/")


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="user_images/")
    is_online = models.BooleanField(default=False)

src/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from user.models import UserImage


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

UserImageFormSet = forms.inlineformset_factory(parent_model=User, model=UserImage, fields=["image"])

class EditProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email"]

src/user/views.py
import json
import re
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.forms import inlineformset_factory, model_to_dict
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated

from user.models import UserImage

from .forms import EditProfileForm, SignupForm, UserImageFormSet

# Create your views here.


def sign_up(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if (form.is_valid()):
            form.save()
            return redirect("login")
    else:
        form = SignupForm()

    return render(request, "registration/signup.html", {"form": form})


@login_required()
def profile(request):
    user = request.user
    user_json = json.dumps(model_to_dict(
        user), indent=4, cls=DjangoJSONEncoder)
    return render(request, "user/profile.html", {"user_json": user_json, "user": user})


@login_required()
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=user)
        image_formset = UserImageFormSet(
            request.POST, request.FILES, instance=user)
        if form.is_valid() and image_formset.is_valid():
            form.save(commit=True)
            image_formset.save()
            return HttpResponseRedirect(reverse("account_profile"))
        else:
            return render(request, "user/edit_profile.html", {"form": form, "image_formset": image_formset})
    elif request.method == "GET":
        form = EditProfileForm(instance=user)
        image_formset = UserImageFormSet(instance=user)
        print(image_formset[0].instance.image)
        return render(request, "user/edit_profile.html", {"form": form, "image_formset": image_formset})
    else:
        raise "What a hell?"


@api_view(["POST"])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def set_online_status(request):
    user = request.user
    user.profile.is_online = request.data["isConnected"]
    print(user.profile.is_online)
    user.profile.save()
    return JsonResponse({ "ok": True })

src/user/templates/user/edit_profile.html
<h2>Edit profile</h2>
<div>
    <form enctype="multipart/form-data"
          action="{% url "edit_profile" %}"
          method="post">
        {% csrf_token %}
        {% if form.errors or image_formset.errors %}
            <div>
                <div>Ошибки:</div>
                <div>
                    {{ form.errors }}
                    {{ image_formset.errors }}
                </div>
            </div>
        {% endif %}
        {{ form }}
        {{ image_formset }}
        {% for image_form in image_formset %}
            {% if image_form.instance.image %}
                <img style="width: 400px;
                            height: 300px"
                     src="{{ image_form.instance.image.url }}"
                     alt="No image">
            {% endif %}
        {% endfor %}
        <button type="submit">Подтвердить</button>
    </form>
</div>

src/user/templates/user/profile.html
<h2>Profile</h2>

<a href="{% url "product:index" %}">Все товары</a>

<pre>{{ user_json }}</pre>

<div>
    <div>
        <img src="" alt="">
    </div>

    <div>
        Username: {{ user.username }}
    </div>
    <div>
        First name: {{ user.first_name }}
    </div>
    <div>
        Last name: {{ user.last_name }}
    </div>
    <div>
        Email: {{ user.email }}
    </div>
    <div>
        <a href="{% url "product:purchase_history" %}">История покупок</a>
    </div>

    <div>
         <a href="{% url "edit_profile" %}">Редактировать профиль</a>
    </div>

    <div>
        <form action="{% url 'logout' %}?next={% url "login" %}" method="post">
            {% csrf_token %}
            <button type="submit">Выйти</button>
        </form>
    </div>
</div>