src/chat/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from rest_framework.authtoken.views import obtain_auth_token

from . import views


router = DefaultRouter()

handler404 = views.error_404

app_name = "chat"
urlpatterns = [
    path("open_chat/<int:user_id>", views.open_chat, name="open_chat"),
    path("send_message/", views.send_message, name="send_message"),
    path("alter_message/", views.alter_message, name="alter_message"),
    path("delete_message/", views.delete_message, name="delete_message"),
    path("list/", views.chat_list),

    path('api-token-auth/', obtain_auth_token),
    path("is_authed/", views.is_authed),
    path("<int:companion_id>/", views.get_chat_data),
    path("api/", include(router.urls)),
]

src/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("user.urls")),
    path('product/', include("product.urls")),
    path('chat/', include("chat.urls")),
    path('social_network/', include("social_network.urls")),


    path("", RedirectView.as_view(pattern_name="product:index"), name="default")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/social_network/urls.py
from django.urls import path

from . import views

app_name="social_network"
urlpatterns = [
    path("find_users/", view=views.find_users, name="find_users"),
    path("user_profile/<int:user_id>/", view=views.user_profile, name="user_profile"),
    path("send_friendship_request/<int:user_id>/", view=views.send_friendship_request, name="send_friendship_request"),
    path("accept_friendship_request/<int:user_id>/", view=views.accept_friendship_request, name="accept_friendship_request"),
    path("friends_list/", view=views.get_friends_list, name="friends_list"),
    path("my_profile/", view=views.my_profile, name="my_profile"),
    path("create_publication/", view=views.create_publication, name="create_publication"),
    path("delete_publication/<int:publication_id>", view=views.delete_publication, name="delete_publication"),
    path("profile_images/", view=views.profile_images, name="profile_images"),
    path("process_notification/<int:notification_id>/", view=views.process_notification, name="process_notification"),
    path("go_to_chat/<int:user_id>/", view=views.go_to_chat, name="go_to_chat"),
    path("communities/", view=views.get_communities, name="get_communities"),
    path("communities/create/", view=views.create_community, name="create_community"),
    path("communities/<int:community_id>/", view=views.get_community, name="get_community"),
    path("communities/publication/add", view=views.create_community_publication, name="add_community_publication"),
    path("communities/<int:community_id>/settings/", view=views.community_settings, name="community_settings"),
]

src/social_network/models.py
from django.db import models
from django.db.models import Q, F, CheckConstraint, TextField
from django.db.models.functions import Length
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework.authentication import get_user_model
from django.core.exceptions import ValidationError
from rest_framework.fields import MinLengthValidator

# Create your models here.

TextField.register_lookup(Length)

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="social_network_profile")
    friends = models.ManyToManyField(to="self", through="Friendship", symmetrical=True)

    def __str__(self) -> str:
        return self.user.username
    

class Publication(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="publications")
    text = models.TextField(validators=[
        MinLengthValidator(1, "the field must contain at least 10 character")
    ])
    images = models.ManyToManyField("ProfileImage", related_name="publications")

    class Meta:
        constraints = [
            CheckConstraint(check=Q(text__length__gte=1), name="text_min_length")
        ]
    

class FriendshipRequestStatus(models.TextChoices):
    ACTIVE = "ACTIVE"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    

class FriendshipRequest(models.Model):

    from_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="from_profile")
    to_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="to_profile")
    status = models.CharField(choices=FriendshipRequestStatus, max_length=20, default=FriendshipRequestStatus.ACTIVE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["from_profile", "to_profile"], name="friendshiprequest_unique_constraint"),
            models.CheckConstraint(check=~Q(from_profile=F("to_profile")), name="friendshiprequest_themselves_constraint")
        ]

    def create_friendship_request(from_profile, to_profile):
        if (Friendship.are_friends(from_profile, to_profile)):
            raise ValidationError(f"{from_profile} and {to_profile} are already friends.")
        return FriendshipRequest.objects.get_or_create(from_profile=from_profile, to_profile=to_profile)[0]

    def accept(self):
        self.status = FriendshipRequestStatus.ACCEPTED
        self.save()
        Friendship.objects.get_or_create(friend_1=self.from_profile, friend_2=self.to_profile)


class Friendship(models.Model):
    friend_1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friend_1")
    friend_2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friend_2")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["friend_1", "friend_2"], name="friendship_unique_constraint"),
            models.CheckConstraint(check=~Q(friend_1=F("friend_2")), name="friendship_themselves_constraint")
        ]

    def are_friends(profile_1, profile_2):
        return Friendship.objects.filter(friend_1=profile_1, friend_2=profile_2).exists()

    def get_friends(profile):
        return Friendship.objects.filter(friend_1=profile)
    

class ProfileImage(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile_images")
    image = models.ImageField(upload_to="profile_images/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.profile}'s image"


class Notification(models.Model):
    to_profile = models.ManyToManyField(Profile, related_name="notifications")
    content = models.TextField(max_length=200)
    url = models.URLField(max_length=200)




class CommunityMemberStatus(models.TextChoices):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    READER = "READER"
    WRITER = "WRITER"


class CommunityMember(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    community = models.ForeignKey("Community", on_delete=models.CASCADE)
    status = models.CharField(choices=CommunityMemberStatus, max_length=50, default=CommunityMemberStatus.WRITER)
    ban_until = models.DateTimeField(null=True, blank=True)


    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["community", "profile"], name="communitymember_unique_constraint"),
            models.UniqueConstraint(fields=["community"], condition=Q(status=CommunityMemberStatus.OWNER), name="communitymember_owner_unique_constraint"),
        ]

    def save(self, *args, **kwargs):
        print("save community member")
        if (self.ban_until and self.ban_until <= timezone.now()):
            raise ValidationError("ban_until must be greater than timezone.now()")
        return super().save(*args, **kwargs)



class Community(models.Model):
    title = models.CharField(max_length=200)
    members = models.ManyToManyField(Profile, through=CommunityMember)

    def create_community(title, owner):
        community = Community(title=title)
        community.save()
        for m in members:
            user = get_object_or_404(Profile, pk=m)
            community_member = CommunityMember(profile=user, community=community)
            if (owner.social_network_profile == community_member.profile):
                community_member.status = CommunityMemberStatus.OWNER
            community_member.save()

src/social_network/forms.py
from django.forms import ModelForm

from social_network.models import Community, CommunityPublication


class CommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = ("title", )

class CommunityPublicationForm(ModelForm):
    class Meta:
        model = CommunityPublication
        fields = ("text", )

src/social_network/views.py
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from rest_framework.authentication import get_user_model
from rest_framework.authtoken.models import Token

from social_network.decorators import use_notifications
from social_network.forms import CommunityForm
from social_network.models import Community, CommunityMember, CommunityMemberStatus, Friendship, FriendshipRequest, FriendshipRequestStatus, Notification, ProfileImage, Publication
from user.models import Profile

User = get_user_model()

# Create your views here.


@login_required
def find_users(request):
    friendship_requests = FriendshipRequest.objects.filter(
        to_profile=request.user.social_network_profile, status=FriendshipRequestStatus.ACTIVE)
    users = User.objects.exclude(id=request.user.id)
    return render(request, "social_network/find_users.html", {"users": users, "friendship_requests": friendship_requests})


@login_required()
def user_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, "social_network/user_profile.html", {"user": user, "publications": user.social_network_profile.publications.all()})


@login_required()
@use_notifications()
def my_profile(request):
    user = request.user
    print(request.notifications)
    return render(request, "social_network/my_profile.html", {"user": user, "publications": user.social_network_profile.publications.all(), "images": user.social_network_profile.profile_images.all()})


@login_required()
@require_POST
def send_friendship_request(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    try:
        friendship_request = FriendshipRequest.create_friendship_request(
            from_profile=request.user.social_network_profile, to_profile=user.social_network_profile)
        friendship_request.save()
        return redirect("social_network:user_profile", user_id)
    except Exception as e:
        return HttpResponse(e, status=500)


@login_required()
@require_POST
def accept_friendship_request(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    friendship_request = FriendshipRequest.objects.get(
        from_profile=user.social_network_profile, to_profile=request.user.social_network_profile)
    friendship_request.accept()
    return redirect("social_network:user_profile", user_id)


@login_required()
def get_friends_list(request):
    friends = Friendship.get_friends(
        profile=request.user.social_network_profile)
    return render(request, "social_network/friends_list.html", {"friends": friends})


@login_required()
@require_POST
def create_publication(request):
    user = request.user
    text = request.POST.get("publication_text")
    if len(text.strip()) < 1:
        return HttpResponseServerError("publication text must be at least 1 character")
    images = request.POST.getlist("images")
    publication = Publication(text=text, profile=user.social_network_profile)
    publication.save()
    publication.images.set(images)
    notification = Notification(content=f"{user.username} опубликовал новый пост. Спешите увидеть.", url=reverse(
        "social_network:user_profile", args=[user.id]))
    notification.save()
    friends = Friendship.objects.filter(friend_1=user.social_network_profile)
    notification.to_profile.set(
        list(friends.values_list("friend_2", flat=True)))
    return redirect("social_network:my_profile")


@login_required()
@require_GET
def delete_publication(request, publication_id):
    pub = get_object_or_404(Publication, pk=publication_id,
                            profile=request.user.social_network_profile)
    pub.delete()
    return redirect("social_network:my_profile")


@login_required()
@require_http_methods(["GET", "POST"])
def profile_images(request):
    images = request.FILES.getlist("images")
    if request.method == "POST" and images:
        for image in images:
            profile_image = ProfileImage(
                image=image, profile=request.user.social_network_profile)
            profile_image.save()
        return redirect("social_network:profile_images")
    images = ProfileImage.objects.filter(
        profile=request.user.social_network_profile)
    return render(request, "social_network/profile_images.html", {"images": images})


def process_notification(request, notification_id):
    notification = get_object_or_404(
        Notification, pk=notification_id, to_profile=request.user.social_network_profile)
    url = notification.url
    notification.delete()
    return HttpResponseRedirect(url)


@login_required()
def go_to_chat(request, user_id):
    token = Token.objects.get_or_create(user=request.user)
    return HttpResponseRedirect(f"http://localhost:5173/chat/{user_id}/{token[0]}")

@login_required()
def get_communities(request):
    user = request.user
    communities = Community.objects.filter(members=user.social_network_profile)
    return render(request, "social_network/get_communities.html", { "communities" : communities })



@login_required()
@require_http_methods(["GET", "POST"])
def create_community(request):
    # if (request.method == "GET"):
    #     form = CommunityForm()
    #     return render(request, "social_network/create_community.html", {"form": form})
    # form = CommunityForm(request.POST)
    # if (form.is_valid()):
    #     form.save()
    # return render(request, "social_network/create_community.html", {"form": form})
    CommunityMembersInlineFormSet = inlineformset_factory(Community, CommunityMember, fields=["status", "ban_until", "profile"])
    if (request.method == "GET"):
        form = CommunityForm()
        formset = CommunityMembersInlineFormSet()
        return render(request, "social_network/create_community.html", {"form": form, "formset": formset})
    form = CommunityForm(request.POST)
    formset = CommunityMembersInlineFormSet()
    if (form.is_valid()):
        community = form.save()
        CommunityMember.objects.create(profile=request.user.social_network_profile, status=CommunityMemberStatus.OWNER, community=community)
        formset = CommunityMembersInlineFormSet(request.POST, instance=community)
        if (formset.is_valid()):
            formset.save()
    return render(request, "social_network/create_community.html", {"form": form, "formset": formset})

src/social_network/templates/social_network/community_settings.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            {{formset}}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

src/social_network/templates/social_network/create_community.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <form action="" method="post">
      {% csrf_token %}
      {{form}}
      {{formset}}
      <button type="submit">Submit</button>
    </form>
  </div>
{% endblock content %}

src/social_network/templates/social_network/find_users.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <a href="{% url "social_network:my_profile" %}">Мой профиль</a>
    <a href="{% url "social_network:friends_list" %}">К списку друзей</a>
    <div>
      {% for friendship_request in friendship_requests %}
        <span>From: {{ friendship_request.from_profile }}</span>
        <form action="{% url "social_network:accept_friendship_request" friendship_request.from_profile.user.id %}" method="post">
          {% csrf_token %}
          <button type="submit">Accept</button>
        </form>
      {% endfor %}
    </div>
    <div class="users d-flex flex-column" style="gap: 50px;">
      {% for user in users %}
      <div class="d-flex border p-3">
        <div class="col-1">
          {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}"
                 alt=""
                 class="w-100 border border-success"
                 style="aspect-ratio: 1;
                        object-fit: cover;
                        border-radius: 50%">
          {% else %}
            <img src="https://static.vecteezy.com/system/resources/thumbnails/027/951/137/small_2x/stylish-spectacles-guy-3d-avatar-character-illustrations-png.png"
                 alt=""
                 class="w-100 border border-success"
                 style="aspect-ratio: 1;
                        object-fit: cover;
                        border-radius: 50%">
          {% endif %}
        </div>
        <div class="flex-grow-1">
          <a href="{% url "social_network:user_profile" user.id %}">{{ user.username }}</a>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
{% endblock content %}

src/social_network/templates/social_network/friends_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    {% for friend in friends %}
      <div>{{ friend.friend_2 }}</div>
    {% endfor %}
  </div>
{% endblock content %}

src/social_network/templates/social_network/get_communities.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    {% for community in communities %}
      <div>
        <a href="{% url "social_network:get_community" community.id %}">
            <span>{{ community.title }}</span>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

src/social_network/templates/social_network/get_community.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div>
            Community: {{community.id}}
        </div>
        <div><a href="{% url "social_network:community_settings" community.id %}">Настройки</a></div>
        <div>
            {% for pub in publications %}
                <div style="border: 1px solid gray; margin-bottom: 10px;">
                    <p>{{pub.text}}</p>
                    <span>{{pub.publicated_at|date:"l. j F o. G:i"}}</span>
                </div>
            {% endfor %}
        </div>
        <div>
            <form action="{% url "social_network:add_community_publication" %}?community_id={{community.id}}" method="post">
                {% csrf_token %}
                {{ form }}
                <button type="Submit">Отправить</button>
            </form>
        </div>
    </div>
{% endblock content %}

src/social_network/templates/social_network/my_profile.html
{% extends "base.html" %}
{% block content %}
  <style>
    option:checked {
      border: 1px solid red;
    }
  </style>
  <div class="container">
    <div>
      {% for notification in request.notifications %}
        <a href="{% url "social_network:process_notification" notification.id %}">{{ notification.content }}</a>
      {% endfor %}
    </div>
    <div>
      <a href="{% url "social_network:friends_list" %}">Друзья</a>
    </div>
    <div>
      <a href="{% url "social_network:find_users" %}">Поиск людей</a>
    </div>
    <div>{{ user.username }}</div>
    <div>
      <a href="{% url "social_network:profile_images" %}">Мои фотографии</a>
    </div>
    <form action="{% url "social_network:create_publication" %}" method="post">
      {% csrf_token %}
      <textarea name="publication_text" id="1"></textarea>
      <label for="images">Choose images:</label>
      <select class="d-flex flex-column" name="images" id="images" multiple>
        {% for image in images %}
          <option value="{{ image.id }}"
                  style="background-image: url({{ image.image.url }});
                         width: 200px;
                         height: 100px;
                         background-size:cover;
                         margin: 20px 0"></option>
        {% endfor %}
      </select>
      <button type="submit">Опубликовать</button>
    </form>
    <div>
      {% for publication in publications %}
        <div>
          <span>Publication</span>
          <a href="{% url "social_network:delete_publication" publication.id %}">X</a>
          <div>{{ publication.text }}</div>
          <div>
            {% for image in publication.images.all %}
              <img src="{{ image.image.url }}" alt="" style="width: 300px; aspect-ratio: 16/9; object-fit: cover;">
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

src/social_network/templates/social_network/profile_images.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      {% for image in images %}
        <div class="col-3">
          <img src="{{ image.image.url }}"
               alt=""
               class="w-100"
               style="aspect-ratio: 16 / 9;
                      object-fit: cover">
          <span>Uploaded at: {{ image.uploaded_at }}</span>
        </div>
      {% endfor %}
    </div>
    <form action="{% url "social_network:profile_images" %}"
          method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="images" multiple>
      <button type="submit">Отправить</button>
    </form>
  </div>
{% endblock content %}

src/social_network/templates/social_network/user_profile.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div>{{ user.username }}</div>
    <form action="{% url "social_network:send_friendship_request" user.id %}"
          method="post">
      {% csrf_token %}
      <button type="submit">Отправить запрос в друзья</button>
    </form>
    <a href="{% url "social_network:go_to_chat" user.id %}">Сообщения</a>
    <div>
      {% for publication in publications %}
      <div>
        <span>Publication</span>
        <div>{{ publication.text }}</div>
        <div>
          {% for image in publication.images.all %}
            <img src="{{ image.image.url }}" alt="" style="width: 300px; aspect-ratio: 16/9; object-fit: cover;">
          {% endfor %}
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
{% endblock content %}