src/chat/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from rest_framework.authtoken.views import obtain_auth_token

from . import views


router = DefaultRouter()

handler404 = views.error_404

app_name = "chat"
urlpatterns = [
    path("open_chat/<int:user_id>", views.open_chat, name="open_chat"),
    path("send_message/", views.send_message, name="send_message"),
    path("alter_message/", views.alter_message, name="alter_message"),
    path("delete_message/", views.delete_message, name="delete_message"),
    path("list/", views.chat_list),

    path('api-token-auth/', obtain_auth_token),
    path("is_authed/", views.is_authed),
    path("<int:companion_id>/", views.get_chat_data),
    path("api/", include(router.urls)),
]

src/product/urls.py
from django.urls import path


from . import views


app_name = "product"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("add_product_to_basket/<int:product_id>/", view=views.add_product_to_basket, name="add_product_to_basket"),
    path("remove_product_from_basket/<int:product_id>/", view=views.remove_product_from_basket, name="remove_product_from_basket"),
    path("basket/", view=views.basket, name="basket"),
    path("approve_basket/", views.approve_basket, name="approve_basket"),
    path("payment_success/<int:basket_id>", views.payment_success, name="payment_success"),
    path("purchase_history/", views.purchase_history, name="purchase_history"),
    path("about_product/<int:product_id>/", views.about_product, name="about_product"),

    path("add_like_on_review/<int:review_id>/", view=views.add_like_on_review, name="add_like_on_review")
]

src/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("user.urls")),
    path('product/', include("product.urls")),
    path('chat/', include("chat.urls")),
    path('social_network/', include("social_network.urls")),


    path("", RedirectView.as_view(pattern_name="product:index"), name="default")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/social_network/urls.py
from django.urls import path

from . import views

app_name="social_network"
urlpatterns = [
    path("find_users/", view=views.find_users, name="find_users"),
    path("user_profile/<int:user_id>/", view=views.user_profile, name="user_profile"),
    path("send_friendship_request/<int:user_id>/", view=views.send_friendship_request, name="send_friendship_request"),
    path("accept_friendship_request/<int:user_id>/", view=views.accept_friendship_request, name="accept_friendship_request"),
    path("friends_list/", view=views.get_friends_list, name="friends_list"),
    path("my_profile/", view=views.my_profile, name="my_profile"),
    path("create_publication/", view=views.create_publication, name="create_publication"),
    path("delete_publication/<int:publication_id>", view=views.delete_publication, name="delete_publication"),
    path("profile_images/", view=views.profile_images, name="profile_images"),
    path("process_notification/<int:notification_id>/", view=views.process_notification, name="process_notification"),
    path("go_to_chat/<int:user_id>/", view=views.go_to_chat, name="go_to_chat"),
    path("communities/", view=views.get_communities, name="get_communities"),
    path("communities/create/", view=views.create_community, name="create_community"),
    path("communities/<int:community_id>/", view=views.get_community, name="get_community"),
    path("communities/publication/add", view=views.create_community_publication, name="add_community_publication"),
    path("communities/<int:community_id>/settings/", view=views.community_settings, name="community_settings"),
]

src/product/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, BaseConstraint, CheckConstraint, ForeignKey, Sum, UniqueConstraint, F
from django.core.validators import MinLengthValidator
from django.test.testcases import CheckCondition


# Create your models here.
class ProductImage(models.Model):
    image = models.ImageField(upload_to="images/")
    product = models.ForeignKey("Product", on_delete=models.CASCADE)


class ProductCategory(models.Model):
    category_name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.category_name


class Brand(models.Model):
    brand_name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.brand_name


class Manufacturer(models.Model):
    title = models.CharField(max_length=200)
    country = models.CharField(max_length=200)

    def __str__(self) -> str:
        return f"{self.title}. {self.country}"


class Product(models.Model):
    title = models.CharField(max_length=200, validators=[
        MinLengthValidator(1)
    ])
    price = models.DecimalField(decimal_places=2, max_digits=12)
    discount = models.DecimalField(
        decimal_places=2, max_digits=3, null=True, blank=True)
    ingredients = models.TextField(max_length=1000, default="", blank=True)
    description = models.TextField(max_length=1000, default="", blank=True)
    category = models.ForeignKey(
        ProductCategory, on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey(
        Brand, on_delete=models.SET_NULL, null=True, blank=True)
    manufacturer = models.ForeignKey(
        Manufacturer, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return self.title

    def count_price(self):
        if (self.discount):
            return round(self.price * (1 - self.discount), 2)
        else:
            return self.price

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(discount__gte=0.01) & Q(discount__lte=1),
                name="discount_check"
            )
        ]


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="reviews")
    text = models.TextField(max_length=1000)
    rating = models.IntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "product"], name="product_review__constraint"),
            models.CheckConstraint(
                check=Q(rating__gte=0) & Q(rating__lte=10),
                name="rating_check",
                violation_error_message="Provide rating value between 0 and 10"
            )
        ]

    def __str__(self) -> str:
        return f"User: {self.user}. Product: {self.product}"


class ProductReviewLike(models.Model):
    review = models.ForeignKey(ProductReview, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["review", "user"], name="review_like__constraint",
                                    violation_error_message="Only 1 like per user on review is allowed")
        ]

    def __str__(self) -> str:
        return f"User: {self.user} liked review: {self.review}"


class BasketStatus(models.TextChoices):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

class ProductBasket(models.Model):
    product_count = models.IntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    basket = models.ForeignKey("Basket", on_delete=models.CASCADE)
    archived_price = models.DecimalField(decimal_places=2, max_digits=12, null=True, blank=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=["basket", "product"],
                             name="productbasket_constraint"),
        ]

    def __str__(self) -> str:
        return f"Basket: {self.basket.pk}. Product: {self.product.title}"




class Basket(models.Model):

    class Meta:
        constraints = [
            UniqueConstraint(fields=["owner", "status"], condition=Q(status="ACTIVE"), name="basket_status_active_unique_constraint"),
        ]

    products = models.ManyToManyField(Product, through=ProductBasket)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True)
    status = models.CharField(choices=BasketStatus, max_length=50)

    def count_total_price(self):
        if self.status == BasketStatus.ACTIVE:
            price = 0
            products = self.products.annotate(
                count_in_basket=F("productbasket__product_count"))
            for product in products:
                price += product.count_price() * product.count_in_basket
            return price
        else:
            price = 0
            products = self.productbasket_set.all()
            for product in products:
                price += product.archived_price * product.product_count
            return price
    
    def count_products(self):
        result = self.products.annotate(
            count_in_basket=F("productbasket__product_count")
        ).aggregate(count=Sum("count_in_basket", default=0))
        return result.get("count")

    def __str__(self):
        return F"{self.owner}: {self.status}"

class BasketArchive(models.Model):
    user = ForeignKey(User, on_delete=models.CASCADE)
    data = models.JSONField(default=dict)

src/product/forms.py
from django import forms

from product.models import ProductReview


class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        exclude = ["user", "product"]

src/product/views.py
import json
import uuid
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import F
from django.forms import model_to_dict
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from rest_framework import serializers
from yookassa import Payment

from product.filters import ProductFilter
from product.forms import ProductReviewForm
from product.models import Basket, BasketArchive, BasketStatus, Product, ProductBasket, ProductCategory, ProductImage, ProductReview, ProductReviewLike

# Create your views here.


def index(request):
    basket = _get_basket(request)
    filter = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request, "product/index.html", {"basket": basket, "filter": filter})


def add_product_to_basket(request, product_id):
    basket = _get_basket(request)
    try:
        product_basket = ProductBasket.objects.get(
            basket=basket, product=product_id)
        product_basket.product_count += 1
    except (ProductBasket.DoesNotExist, KeyError):
        product = get_object_or_404(Product, pk=product_id)
        product_basket = ProductBasket.objects.create(
            basket=basket, product=product, product_count=1)
    product_basket.save()
    redirect_to = request.GET.get("next")
    return HttpResponseRedirect(redirect_to)


def remove_product_from_basket(request, product_id):
    basket = _get_basket(request)
    try:
        product_basket = ProductBasket.objects.get(
            basket=basket, product=product_id)
        product_basket.product_count -= 1
    except (ProductBasket.DoesNotExist, KeyError):
        pass
    if (product_basket.product_count == 0):
        product_basket.delete()
    else:
        product_basket.save()
    redirect_to = request.GET.get("next")
    return HttpResponseRedirect(redirect_to)


def basket(request):
    basket = _get_basket(request)
    productbasketlist = ProductBasket.objects.filter(basket=basket.pk)
    basket_total_count = basket.count_total_price()
    return render(request, "product/basket.html", {"productbasketlist": productbasketlist, "basket_total_count": basket_total_count})


def about_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user:
        try:
            product_review = ProductReview.objects.get(
                user=request.user, product=product)
        except ProductReview.DoesNotExist:
            product_review = ProductReview(product=product, user=request.user)
        if request.method == "POST":
            product_review_form = ProductReviewForm(
                data=request.POST, instance=product_review)
            if product_review_form.is_valid():
                product_review_form.save()
        else:
            product_review_form = ProductReviewForm(instance=product_review)
    return render(request, "product/about.html", {"product": product, "product_review_form": product_review_form})


@login_required()
def approve_basket(request):
    basket = _get_basket(request)
    basket_total_count = basket.count_total_price()
    payment = Payment.create({
        "amount": {
            "value": basket_total_count,
            "currency": "RUB"
        },
        "confirmation": {
            "type": "redirect",
            "return_url": request.build_absolute_uri(reverse("product:payment_success", args=[basket.pk]))
        },
        "capture": True,
        "description": "Заказ №1"
    }, uuid.uuid4())
    return HttpResponseRedirect(payment.confirmation.confirmation_url)


@login_required()
def payment_success(request, basket_id):
    # return render(request, "product/payment_success.html")

    class ProductImageSerializer(serializers.ModelSerializer):
        image_url = serializers.ImageField(source="image") 

        class Meta:
            model = ProductImage
            fields = ["image_url"]

    class ProductSerializer(serializers.ModelSerializer):
        images = ProductImageSerializer(source="productimage_set", many=True)

        class Meta:
            model = Product
            exclude = []

    class ProductBasketSerializer(serializers.ModelSerializer):
        product_info = ProductSerializer(source="product")

        class Meta:
            model = ProductBasket
            fields = ["product_count", "product_info"]

    class BasketSerializer(serializers.ModelSerializer):
        basket_id = serializers.ReadOnlyField(source="id")
        basket_total_count = serializers.ReadOnlyField(
            source="count_total_price")
        products = ProductBasketSerializer(
            source="productbasket_set", many=True)

        class Meta:
            model = Basket
            fields = ["basket_id", "basket_total_count", "products"]

    basket = _get_basket(request)
    if basket_id != basket.id:
        raise Http404()
    basket_data = {
        "basket_id": basket.pk,
        "basket_total_count": basket.count_total_price(),
        # "products": list(
        #     basket.products.all().annotate(product_count=F("productbasket__product_count"),
        #                                    images=F("productbasket__product__productimage__image")).order_by("id").values()
        # "products": ProductSerializer(basket.products.all(), many=True).data
    }
    basket_data = BasketSerializer(basket).data
    basket_archive = BasketArchive(
        user=request.user, data=json.dumps(basket_data, cls=DjangoJSONEncoder))
    basket_archive.save()


    basket.status = BasketStatus.ARCHIVED
    basket_products = basket.productbasket_set.all()
    for product in basket_products:
        product.archived_price = product.product.price
        product.save()
    basket.save()
    _get_basket(request)
    return HttpResponseRedirect(reverse("product:purchase_history"))
    # return HttpResponse([   (basket.data)["basket_total_count"] for basket in all_baskets])


@login_required()
def purchase_history(request):
    all_baskets = request.user.basket_set.filter(status=BasketStatus.ARCHIVED)
    return render(request, "product/basket_archive.html", {"baskets": all_baskets})


def _get_basket(request):
    print("_get_basket")
    if request.user and request.user.is_authenticated:
        # return Basket.objects.get_or_create(owner=request.user, status=Basket.Status.OPEN)[0]
        print("try get basket from authed user")
        return Basket.objects.get_or_create(owner=request.user, status=BasketStatus.ACTIVE)[0]
    try:
        basket_id = request.session.get("basket_id")
        if (basket_id == None):
            raise KeyError("No basket_id in session")
        basket = Basket.objects.get(pk=basket_id)
    except (KeyError, Basket.DoesNotExist) as e:
        print(e)
        basket = Basket.objects.create()
        basket.save()
        request.session["basket_id"] = basket.pk
        request.session
    return basket


@login_required()
def add_like_on_review(request, review_id):
    try:
        like = ProductReviewLike(user=request.user, review_id=review_id)
        like.validate_constraints()
        like.save()
    except ValidationError:
        ProductReviewLike.objects.get(
            user=request.user, review_id=review_id).delete()
    redirect_to = request.GET.get("next")
    return HttpResponseRedirect(redirect_to)

src/product/templates/product/about.html
{% extends "base.html" %}
{% block content %}
  <style>
    .text-1 {
      font-weight: 600;
    }
  </style>
  <div class="container">
    <h2>About product: {{ product.title }}</h2>
    <div class="row pt-5">
      <div class="col-8">
        <div class="w-100">{% include "product/about__image_gallery.html" with product=product %}</div>
      </div>
      <div class="col-4">
        <a href="{% url "product:index" %}">Все товары</a>
        <div>
          <div>Описание товара</div>
          <div>
            <div class="text-1">Состав:</div>
             {{ product.ingredients }}
          </div>
          <div>
            <div class="text-1">Производитель:</div>
            <a href="{% url "product:index" %}?manufacturer={{product.manufacturer.id}}">
              {{ product.manufacturer.title }}. {{ product.manufacturer.country }}
            </a>
          </div>
          <div>
            <div class="text-1">Бренд:</div>
            <a href="{% url "product:index"  %}?brand={{product.brand_id}}">
              {{ product.brand.brand_name }}
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div>Отзывы</div>
      <form action="{{ request.get_full_path|urlencode }}" method="post">
        {% csrf_token %}
        {{ product_review_form }}
        <button type="submit">Submit</button>
      </form>
      <ul>
        {% for review in product.reviews.all %}
          <li>
            <div style="display: flex;">
              {% with ""|center:10 as range %}
                {% for _ in range %}
                  {% if forloop.counter <= review.rating %}
                    <div style="width: 10px; height: 20px; background-color: #000;"></div>
                  {% else %}
                    <div style="width: 10px; height: 20px; background-color: #999;"></div>
                  {% endif %}
                {% endfor %}
              {% endwith %}
            </div>
            <div>Автор: {{ review.user }}</div>
            <p>{{ review.text }}</p>
            <div>
              <a href="{% url "product:add_like_on_review" review.id %}?next={{ request.get_full_path|urlencode }}">{{ review.likes.count }} likes</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}

src/product/templates/product/about__image_gallery.html
<div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
        {% for image in product.productimage_set.all %}
            <div {% if forloop.first %}class="carousel-item active"{% else %}class="carousel-item"{% endif %}>
                <img src="{{ image.image.url }}" class="d-block w-100" style="aspect-ratio: 16 / 9; object-fit: cover;"
                     alt="cartinka">
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExample"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next"
            type="button"
            data-bs-target="#carouselExample"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

src/product/templates/product/basket.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <link rel="stylesheet" href="{% static 'product/style.css' %}">
        <ul style="max-width: 600px;">
            {% for productbasket in productbasketlist %}
                <li class="row">
                    <div class="col-2">
                        {% if productbasket.product.productimage_set.first %}
                            <img class="w-100"
                                 style="aspect-ratio: 16 / 9;
                                        object-fit: cover"
                                 src="{{ productbasket.product.productimage_set.first.image.url }}"
                                 alt="">
                        {% else %}
                            <img class="w-100"
                                 style="aspect-ratio: 16 / 9;
                                        object-fit: cover"
                                 src="https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png"
                                 alt="">
                        {% endif %}
                    </div>
                    <div class="col">
                        <div>Title: {{ productbasket.product.title }}</div>
                        <div>Price: {{ productbasket.product.count_price }}</div>
                    </div>
                    <div class="col-2">
                        <div class="btn btn-secondary">
                            <a href="{% url "product:remove_product_from_basket" productbasket.product.id %}?next={{ request.get_full_path|urlencode }}">-</a>
                            <span>{{ productbasket.product_count }}</span>
                            <a href="{% url "product:add_product_to_basket" productbasket.product.id %}?next={{ request.get_full_path|urlencode }}">+</a>
                        </div>
                    </div>
                </li>
            {% endfor %}
            <div>
                Total <strong>{{ basket_total_count }}</strong>
            </div>
            <a href="{% url "product:index" %}" class="btn btn-secondary">Back to products</a>
            <a href="{% url "product:approve_basket" %}" class="btn btn-success">Approve basket</a>
        </ul>
    </div>
{% endblock content %}

src/product/templates/product/basket_archive.html
{% extends "base.html" %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <h2>История ваших заказов</h2>
        <a href="{% url "product:index" %}">Вернуться к каталогу</a>
        {% for basket in baskets %}
            <div class="card mb-5 align-items-stretch">
                <div class="card-header">
                    <h2>Заказ №: {{ basket.id }}</h2>
                </div>
                <div class="card-body">
                    <span>Итого: {{ basket.count_total_price }} ₽</span>
                    <div class="d-inline-flex w-100 py-4" style="overflow-x: scroll; gap: 20px;">
                        {% for productbasket in basket.productbasket_set.all %}
                        <div class="col-4">
                            <div class="card bg-info text-dark">
                                <img src={{ productbasket.product.productimage_set.first.image.url }} alt="" class="card-img-top h-100" style="aspect-ratio: 16 / 9; object-fit: cover;">
                                <div class="card-body">
                                    <a href="{% url "product:about_product" productbasket.product.id %}" class="fw-semibold fs-5">{{ productbasket.product.title }}</a>
                                    <div>Количество товара: {{ productbasket.product_count }}</div>
                                    <div>Цена: {{productbasket.archived_price}}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

src/product/templates/product/index.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <link rel="stylesheet" href="{% static 'product/style.css' %}">
    <div class="container overflow-hidden">
        <h1>Product index page</h1>
        <div>
            <a href="{% url "account_profile" %}">Profile</a>
            <a href="http://localhost:5173/chats_list">Chat</a>
            <a href="{% url "social_network:my_profile" %}">Social Network Profile</a>
        </div>
        <div>
            <a href="{% url "product:basket" %}">Basket: {{ basket.count_products }}</a>
        </div>
        <form method="get">
            {{ filter.form.as_p }}
            <input type="submit" />
        </form>
        <div class="row g-3">
            {% for product in filter.qs %}
                <div class="col-3">
                    <div class="card text-bg-secondary">
                        {% if product.productimage_set.first %}
                            <img src="{{ product.productimage_set.first.image.url }}"
                                 alt=""
                                 class="card-img-top"
                                 style="aspect-ratio: 16 / 9;
                                        object-fit: cover">
                        {% else %}
                            <img src="https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png"
                                 alt=""
                                 class="card-img-top"
                                 style="aspect-ratio: 16 / 9;
                                        object-fit: cover">
                        {% endif %}
                        <div class="card-body">
                            {% if product.discount %}
                                <div>
                                    <span class="fw-bold text-warning fs-4">{{ product.count_price }} ₽</span>
                                    <span class="fw-bold text-decoration-line-through text-white-50">{{ product.price }}</span>
                                </div>
                            {% else %}
                                <div>
                                    <span class="fw-bold text-warning fs-4">{{ product.price }} ₽</span>
                                </div>
                            {% endif %}
                            <div>
                                <a class="fs-5" href="{% url "product:about_product" product.id %}">{{ product.title }}</a>
                            </div>
                            <div class="mt-2">
                                <a href="{% url "product:add_product_to_basket" product.id %}?next={{ request.get_full_path|urlencode }}"
                                   class="btn btn-primary py-3 w-100">Secondary</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

src/product/templates/product/payment_success.html
<h1>Yohoo</h1>

<div><strong style="color: green; font-size: 25px;">Ириша!</strong> Поздравляю с успешной оплатой!</div>